/**
 * Frontend shared types
 *
 * - Keep BaseEntity intersection to ensure core entities have `id` and timestamp fields
 * - Re-export generated schema types from `types/interfaces`
 * - Provide small frontend-specific extensions (ExtendedIssue, etc.)
 *
 * This file intentionally stays small — most shape comes from generated `interfaces.ts`.
 */

import type {
  CloudEvent as BaseCloudEvent,
  Issue as GeneratedIssue,
  Task as GeneratedTask,
  Comment as GeneratedComment,
  Planning as GeneratedPlanning,
  PlanningMoment as GeneratedPlanningMoment,
  JSONCommit as GeneratedJSONCommit,
  ItemType as GeneratedItemType,
  IssueStatus as GeneratedIssueStatus,
  PlanningStatus as GeneratedPlanningStatus,
  Document as GeneratedDocument,
} from "./types/interfaces";

/* -------------------------------------------------------------------------- */
/* Core generated + base entity glue                                           */
/* -------------------------------------------------------------------------- */

// Minimal common entity fields that the front-end expects to exist on resources.
// These are populated from the JSONCommit (resource_id / resource_data) at runtime.
export interface BaseEntity {
  id: string;
  created_at?: string;
  updated_at?: string;
}

// Re-export and augment generated types with BaseEntity where applicable.
export type CloudEvent = BaseCloudEvent;
export type Issue = GeneratedIssue & BaseEntity;
export type Task = GeneratedTask & BaseEntity;
export type Comment = GeneratedComment & BaseEntity;
// Planning resources include moments; each moment may be referenced in the UI by id.
// Ensure PlanningMoment exposes an id so UI code can key/anchor moments reliably.
export type Planning = GeneratedPlanning & BaseEntity;
export type PlanningMoment = GeneratedPlanningMoment & { id?: string };

export const planningMomentKey = (m: PlanningMoment, idx: number) =>
  m.id ?? `planning-${idx}`;
export type JSONCommit = GeneratedJSONCommit;
export type ItemType = GeneratedItemType;
export type IssueStatus = GeneratedIssueStatus;
export type PlanningStatus = GeneratedPlanningStatus;
export type Document = GeneratedDocument & BaseEntity;

/* -------------------------------------------------------------------------- */
/* Frontend-specific extensions                                                */
/* -------------------------------------------------------------------------- */

// Small UI-focused metadata carried by the front-end (not part of the persisted schema).
export interface ExtendedIssue extends Issue {
  // Generated by front-end, when replaying events
  lastActivity?: string;
}

export interface ExtendedTask extends Task {
  // timestamp when the front-end created/observed the task or last acted on it
  timestamp: string;
}

export interface ExtendedPlanning extends Planning {
  // actor extracted from the most recent related event
  actor?: string;
  // timestamp of latest event for this planning (required for sorting)
  timestamp: string;
}

/* -------------------------------------------------------------------------- */
/* Convenience shapes used by UI and forms                                      */
/* -------------------------------------------------------------------------- */

export interface IssueFormData {
  title: string;
  // the form always supplies a string for these fields (empty string when omitted)
  description: string;
  assignee: string;
}

export interface PatchFormData {
  issueId: string;
  title: string;
  status: string;
  assignee: string;
  description: string;
}

export interface IssueCreateData {
  id: string;
  title: string;
  description?: string;
  status: string;
  assignee?: string | null;
  created_at: string;
}

/* -------------------------------------------------------------------------- */
/* Entity registry & timeline types                                            */
/* -------------------------------------------------------------------------- */

export type EntityTypeMap = {
  issue: ExtendedIssue;
  document: Document;
  planning: ExtendedPlanning;
  task: ExtendedTask;
  comment: Comment;
};

export type EntityType = keyof EntityTypeMap;

export interface TimelineEvent {
  id: string;
  type: "created" | "updated" | "deleted";
  timestamp: string;
  // actor may be omitted for system events, but UI often expects at least a string or 'system'
  actor?: string;
  // data is always present for timeline items (empty object when none)
  data: unknown;
  // original CloudEvent for this timeline entry (required so consumers can inspect schema/subject/etc.)
  originalEvent: CloudEvent;
}

/* Detailed timeline item shapes used across the UI */
export interface TimelineItemData {
  // For comments
  content?: string;
  parent_id?: string | null;
  mentions?: string[];
  edited_at?: string;

  // For status changes
  field?: string;
  old_value?: unknown;
  new_value?: unknown;
  reason?: string;

  // For LLM analysis
  prompt?: string;
  response?: string;
  model?: string;
  confidence?: number;

  // For deployments
  version?: string;
  environment?: string;
  commit_hash?: string;

  // For tasks
  cta?: string;
  description?: string;
  url?: string;
  completed?: boolean;
  deadline?: string;

  // For planning
  moments?: PlanningMoment[];

  // Generic fields
  [key: string]: unknown;
}

/* Export the timeline item type union so components can import it */
export type TimelineItemType =
  | "comment"
  | "status_change"
  | "field_update"
  | "system_update"
  | "llm_analysis"
  | "deployment"
  | "system_event"
  | "issue_created"
  | "issue_updated"
  | "issue_deleted"
  | "task"
  | "planning"
  | "document";

/* Generic helper types */
export type CreateCloudEventData<T extends BaseEntity> = T;
export type PatchCloudEventData = Record<string, unknown>;
export interface DeleteCloudEventData {
  id: string;
  reason?: string;
}
